.PHONY: clean All

All:
	@echo "----------Building project:[ checker - Debug ]----------"
	@cd "src" && "$(MAKE)" -f  "checker.mk"
clean:
	@echo "----------Cleaning project:[ checker - Debug ]----------"
	@cd "src" && "$(MAKE)" -f  "checker.mk" clean
