.PHONY: clean All

All:
	@echo "----------Building project:[ Change_Maker - Debug ]----------"
	@cd "Change_Maker" && "$(MAKE)" -f  "Change_Maker.mk"
clean:
	@echo "----------Cleaning project:[ Change_Maker - Debug ]----------"
	@cd "Change_Maker" && "$(MAKE)" -f  "Change_Maker.mk" clean
