.PHONY: clean All

All:
	@echo "----------Building project:[ Binary_S - Debug ]----------"
	@cd "Binary_S" && "$(MAKE)" -f  "Binary_S.mk"
clean:
	@echo "----------Cleaning project:[ Binary_S - Debug ]----------"
	@cd "Binary_S" && "$(MAKE)" -f  "Binary_S.mk" clean
