.PHONY: clean All

All:
	@echo "----------Building project:[ InsertionSortAlgo - Debug ]----------"
	@cd "InsertionSortAlgo" && "$(MAKE)" -f  "InsertionSortAlgo.mk"
clean:
	@echo "----------Cleaning project:[ InsertionSortAlgo - Debug ]----------"
	@cd "InsertionSortAlgo" && "$(MAKE)" -f  "InsertionSortAlgo.mk" clean
